# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Arcade

on:
  push:
    branches:
      - azure2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Start app for smoke test
        env:
          # Cosmos vars intentionally left empty for CI; index route does not require them
          COSMOS_ENDPOINT: ''
          COSMOS_KEY: ''
        run: |
          source venv/bin/activate
          nohup uvicorn shooter:app --host 127.0.0.1 --port 8000 >/dev/null 2>&1 &
          echo $! > uvicorn.pid

      - name: Wait for server
        run: |
          for i in {1..20}; do
            if curl -sSf http://127.0.0.1:8000/ >/dev/null; then
              exit 0
            fi
            sleep 1
          done
          echo 'Server did not start' >&2
          exit 1

      - name: Smoke test index
        run: |
          curl -fS http://127.0.0.1:8000/ | grep -i "Airplane Shooter"

      - name: Stop app
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then kill $(cat uvicorn.pid) || true; fi

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Arcade'
          slot-name: 'Production'
